###################################################################

# Created by write_sdc on Sun Sep 20 00:44:08 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current uA
set_max_capacitance 100 [current_design]
set_max_fanout 10 [current_design]
set_max_transition 3.63662 [current_design]
set_load -pin_load 100 [get_ports {tx_real[7]}]
set_load -pin_load 100 [get_ports {tx_real[6]}]
set_load -pin_load 100 [get_ports {tx_real[5]}]
set_load -pin_load 100 [get_ports {tx_real[4]}]
set_load -pin_load 100 [get_ports {tx_real[3]}]
set_load -pin_load 100 [get_ports {tx_real[2]}]
set_load -pin_load 100 [get_ports {tx_real[1]}]
set_load -pin_load 100 [get_ports {tx_real[0]}]
set_load -pin_load 100 [get_ports {tx_imag[7]}]
set_load -pin_load 100 [get_ports {tx_imag[6]}]
set_load -pin_load 100 [get_ports {tx_imag[5]}]
set_load -pin_load 100 [get_ports {tx_imag[4]}]
set_load -pin_load 100 [get_ports {tx_imag[3]}]
set_load -pin_load 100 [get_ports {tx_imag[2]}]
set_load -pin_load 100 [get_ports {tx_imag[1]}]
set_load -pin_load 100 [get_ports {tx_imag[0]}]
set_load -pin_load 100 [get_ports tx_done]
set_ideal_network [get_ports clk]
set_ideal_network [get_ports rst_n]
create_clock [get_ports clk]  -period 31.25  -waveform {0 15.625}
set_clock_latency 0  [get_clocks clk]
set_clock_uncertainty -setup 0.9375  [get_clocks clk]
set_clock_uncertainty -hold 0.625  [get_clocks clk]
set_clock_transition -max -rise 0 [get_clocks clk]
set_clock_transition -min -rise 0 [get_clocks clk]
set_clock_transition -max -fall 0 [get_clocks clk]
set_clock_transition -min -fall 0 [get_clocks clk]
set_input_delay -clock clk  -max 6.25  [get_ports rst_n]
set_input_delay -clock clk  -max 6.25  [get_ports {payload[7]}]
set_input_delay -clock clk  -max 6.25  [get_ports {payload[6]}]
set_input_delay -clock clk  -max 6.25  [get_ports {payload[5]}]
set_input_delay -clock clk  -max 6.25  [get_ports {payload[4]}]
set_input_delay -clock clk  -max 6.25  [get_ports {payload[3]}]
set_input_delay -clock clk  -max 6.25  [get_ports {payload[2]}]
set_input_delay -clock clk  -max 6.25  [get_ports {payload[1]}]
set_input_delay -clock clk  -max 6.25  [get_ports {payload[0]}]
set_input_delay -clock clk  -max 6.25  [get_ports {payload_length[6]}]
set_input_delay -clock clk  -max 6.25  [get_ports {payload_length[5]}]
set_input_delay -clock clk  -max 6.25  [get_ports {payload_length[4]}]
set_input_delay -clock clk  -max 6.25  [get_ports {payload_length[3]}]
set_input_delay -clock clk  -max 6.25  [get_ports {payload_length[2]}]
set_input_delay -clock clk  -max 6.25  [get_ports {payload_length[1]}]
set_input_delay -clock clk  -max 6.25  [get_ports {payload_length[0]}]
set_input_delay -clock clk  -max 6.25  [get_ports start_tx]
set_output_delay -clock clk  -max 6.25  [get_ports {tx_real[7]}]
set_output_delay -clock clk  -max 6.25  [get_ports {tx_real[6]}]
set_output_delay -clock clk  -max 6.25  [get_ports {tx_real[5]}]
set_output_delay -clock clk  -max 6.25  [get_ports {tx_real[4]}]
set_output_delay -clock clk  -max 6.25  [get_ports {tx_real[3]}]
set_output_delay -clock clk  -max 6.25  [get_ports {tx_real[2]}]
set_output_delay -clock clk  -max 6.25  [get_ports {tx_real[1]}]
set_output_delay -clock clk  -max 6.25  [get_ports {tx_real[0]}]
set_output_delay -clock clk  -max 6.25  [get_ports {tx_imag[7]}]
set_output_delay -clock clk  -max 6.25  [get_ports {tx_imag[6]}]
set_output_delay -clock clk  -max 6.25  [get_ports {tx_imag[5]}]
set_output_delay -clock clk  -max 6.25  [get_ports {tx_imag[4]}]
set_output_delay -clock clk  -max 6.25  [get_ports {tx_imag[3]}]
set_output_delay -clock clk  -max 6.25  [get_ports {tx_imag[2]}]
set_output_delay -clock clk  -max 6.25  [get_ports {tx_imag[1]}]
set_output_delay -clock clk  -max 6.25  [get_ports {tx_imag[0]}]
set_output_delay -clock clk  -max 6.25  [get_ports tx_done]
